namespace Mpmt.Core.Dtos.Logging
{
    public class AppVendorApiLog
    {
        public string LogId { get; set; }
        public string TransactionId { get; set; }
        public string PartnerTransactionId { get; set; }
        public string PartnerProcessId { get; set; }
        public string TrackerId { get; set; }
        public string RequestInput { get; set; }
        public string ResponseOutput { get; set; }
        public int? ResponseHttpStatus { get; set; }
        public string RequestUrl { get; set; }
        public string RequestHeaders { get; set; }
        public string VendorRequestInput { get; set; }
        public string VendorResponseOutput { get; set; }
        public string VendorRequestURL { get; set; }
        public string VendorRequestHeaders { get; set; }
        public int? VendorResponseHttpStatus { get; set; }
        public bool? VendorResponseStatus { get; set; }
        public string VendorResponseState { get; set; }
        public string VendorResponseMessage { get; set; }
        public string VendorTransactionId { get; set; }
        public string VendorTrackerId { get; set; }
        public string VendorException { get; set; }
        public string VendorExceptionStackTrace { get; set; }
        public string VendorId { get; set; }
        public string VendorType { get; set; }
        public string ClientCode { get; set; }
        public string PartnerCode { get; set; }
        public string AgentCode { get; set; }
        public string MemberId { get; set; }
        public string MemberUserName { get; set; }
        public string MemberName { get; set; }
        public string DeviceCode { get; set; }
        public string IpAddress { get; set; }
        public string Platform { get; set; }
        public string MachineName { get; set; }
        public string Environment { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string VendorRequestInput2 { get; set; }
        public string VendorResponseOutput2 { get; set; }
        public string VendorRequestURL2 { get; set; }
        public string VendorRequestHeaders2 { get; set; }
        public int? VendorResponseHttpStatus2 { get; set; }
        public bool? VendorResponseStatus2 { get; set; }
        public string VendorResponseState2 { get; set; }
        public string VendorResponseMessage2 { get; set; }
        public string VendorTransactionId2 { get; set; }
        public string VendorTrackerId2 { get; set; }
        public string VendorException2 { get; set; }
        public string VendorExceptionStackTrace2 { get; set; }
        public string VendorId2 { get; set; }
        public string VendorType2 { get; set; }
        public string VendorRequestInput3 { get; set; }
        public string VendorResponseOutput3 { get; set; }
        public string VendorRequestURL3 { get; set; }
        public string VendorRequestHeaders3 { get; set; }
        public int? VendorResponseHttpStatus3 { get; set; }
        public bool? VendorResponseStatus3 { get; set; }
        public string VendorResponseState3 { get; set; }
        public string VendorResponseMessage3 { get; set; }
        public string VendorTransactionId3 { get; set; }
        public string VendorTrackerId3 { get; set; }
        public string VendorException3 { get; set; }
        public string VendorExceptionStackTrace3 { get; set; }
        public string VendorId3 { get; set; }
        public string VendorType3 { get; set; }
    }
}
