create or  alter  PROCEDURE [dbo].[usp_get_transaction_by_txnid] --'1436816638773296232924288'  
(  
 @TransactionId varchar(200)  
)  
AS  
BEGIN  
SELECT TOP (1000) [TransactionId]  
      ,[PartnerCode]  
      ,[PartnerName]  
      ,[SourceCurrency]  
      ,[DestinationCurrency]  
      ,[SendingAmount]  
      ,[ServiceCharge]  
      ,[ConversionRate]  
      ,[NetSendingAmount]  
      ,[NetReceivingAmount]  
      ,[CreditSendingAmount]  
      ,[SenderRegistered]  
      ,[MemberId]  
      ,[RecipientRegistered]  
      ,[RecipientId]  
      ,[Sign]  
      ,[PartnerServiceCharge]  
      ,[PartnerCommission]  
      ,[TransactionType]  
      ,[WalletType]  
      ,[CurrentBalance]  
      ,[PreviousBalance]  
      ,[TokenNumber]  
      ,[PaymentTypeId]  
      ,[PaymentType]  
      ,[BankName]  
      ,[BankCode]  
      ,[Branch]  
      ,[AccountHolderName]  
      ,[AccountNumber]  
      ,[WalletName]  
      ,[WalletCode]  
      ,[WalletNumber]  
      ,[WalletHolderName]  
      ,[TransactionApproval]  
      ,[PartnerTransactionId]  
      ,[PartnerTrackerId]  
      ,[PartnerStatus]  
      ,[AgentCode]  
      ,[AgentTransactionId]  
      ,[AgentTrackerId]  
      ,[AgentStatus]  
      ,[GatewayTxnId]  
      ,[ComplianceStatusCode]  
      ,[ComplianceStatus]  
      ,[StatusCode]  
      ,[IpAddress]  
      ,[DeviceId]  
      ,[CreatedUserType]  
      ,[CreatedById]  
      ,[CreatedByName]  
      ,[CreatedDate]  
      ,[UpdatedUserType]  
      ,[UpdatedById]  
      ,[UpdatedByName]  
      ,[UpdatedDate]  
  FROM [MpmtDb].[dbo].[tbl_remit_transaction]  
  WHERE TransactionId = @TransactionId  
  
END  