
CREATE TABLE [dbo].[tbl_exception_logs](
	[LogId] [nvarchar](100) PRIMARY KEY DEFAULT LOWER(NEWID()),
	[UserName] [nvarchar](200) NULL,
	[UserAgent] [nvarchar](500) NULL,
	[RemoteIpAddress] [nvarchar](100) NULL,
	[ControllerName] [nvarchar](100) NULL,
	[ActionName] [nvarchar](100) NULL,
	[QueryString] [nvarchar](2000) NULL,
	[Headers] [nvarchar](max) NULL,
	[RequestUrl] [nvarchar](500) NULL,
	[HttpMethod] [nvarchar](10) NULL,
	[RequestBody] [nvarchar](max) NULL,
	[ExceptionType] [nvarchar](500) NULL,
	[ExceptionMessage] [nvarchar](2000) NULL,
	[ExceptionStackTrace] [nvarchar](max) NULL,
	[InnerExceptionMessage] [nvarchar](max) NULL,
	[InnerExceptionStackTrace] [nvarchar](max) NULL,
	[MachineName] [nvarchar](200) NULL,
	[Environment] [nvarchar](200) NULL,
	[LogLocalDate] [datetime2](7) NULL DEFAULT GETDATE(),
	[LogUtcDate] [datetime2](7) NULL DEFAULT GETUTCDATE()
);


CREATE TABLE [dbo].[tbl_vendor_api_logs] (
	[LogId] [nvarchar](100) PRIMARY KEY DEFAULT (NEWID()),
	[TransactionId] [nvarchar](50) NULL,
	[TrackerId] [nvarchar](50) NULL,
	[RequestInput] [nvarchar](max) NULL,
	[ResponseOutput] [nvarchar](max) NULL,
	[ResponseHttpStatus] [int] NULL,
	[RequestUrl] [nvarchar](500) NULL,
	[RequestHeaders] [nvarchar](max) NULL,
	[VendorRequestInput] [nvarchar](max) NULL,
	[VendorResponseOutput] [nvarchar](max) NULL,
	[VendorRequestURL] [nvarchar](500) NULL,
	[VendorRequestHeaders] [nvarchar](max) NULL,
	[VendorResponseHttpStatus] [int] NULL,
	[VendorResponseStatus] [bit] NULL,
	[VendorResponseState] [nvarchar](50) NULL,
	[VendorResponseMessage] [nvarchar](500) NULL,
	[VendorTransactionId] [nvarchar](50) NULL,
	[VendorTrackerId] [nvarchar](50) NULL,
	[VendorException] [nvarchar](500) NULL,
	[VendorExceptionStackTrace] [nvarchar](max) NULL,
	[VendorId] [nvarchar](50) NULL,
	[VendorType] [nvarchar](50) NULL,
	[VendorRequestInput2] [nvarchar](max) NULL,
	[VendorResponseOutput2] [nvarchar](max) NULL,
	[VendorRequestURL2] [nvarchar](500) NULL,
	[VendorRequestHeaders2] [nvarchar](max) NULL,
	[VendorResponseHttpStatus2] [int] NULL,
	[VendorResponseStatus2] [bit] NULL,
	[VendorResponseState2] [nvarchar](50) NULL,
	[VendorResponseMessage2] [nvarchar](500) NULL,
	[VendorTransactionId2] [nvarchar](50) NULL,
	[VendorTrackerId2] [nvarchar](50) NULL,
	[VendorException2] [nvarchar](500) NULL,
	[VendorExceptionStackTrace2] [nvarchar](max) NULL,
	[VendorId2] [nvarchar](50) NULL,
	[VendorType2] [nvarchar](50) NULL,
	[VendorRequestInput3] [nvarchar](max) NULL,
	[VendorResponseOutput3] [nvarchar](max) NULL,
	[VendorRequestURL3] [nvarchar](500) NULL,
	[VendorRequestHeaders3] [nvarchar](max) NULL,
	[VendorResponseHttpStatus3] [int] NULL,
	[VendorResponseStatus3] [bit] NULL,
	[VendorResponseState3] [nvarchar](50) NULL,
	[VendorResponseMessage3] [nvarchar](500) NULL,
	[VendorTransactionId3] [nvarchar](50) NULL,
	[VendorTrackerId3] [nvarchar](50) NULL,
	[VendorException3] [nvarchar](500) NULL,
	[VendorExceptionStackTrace3] [nvarchar](max) NULL,
	[VendorId3] [nvarchar](50) NULL,
	[VendorType3] [nvarchar](50) NULL,
	[ClientCode] [nvarchar](50) NULL,
	[PartnerCode] [nvarchar](50) NULL,
	[AgentCode] [nvarchar](50) NULL,
	[MemberId] [nvarchar](50) NULL,
	[MemberUserName] [nvarchar](100) NULL,
	[MemberName] [nvarchar](100) NULL,
	[DeviceCode] [nvarchar](500) NULL,
	[IpAddress] [nvarchar](150) NULL,
	[Platform] [nvarchar](100) NULL,
	[MachineName] [nvarchar](100) NULL,
	[Environment] [nvarchar](100) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[UpdatedDate] [datetime2](7) NULL
);

CREATE TABLE [dbo].[tbl_dberrorlogs] (
	LogId BIGINT IDENTITY(1,1) PRIMARY KEY,
	ErrorNumber INT NULL,
	ErrorMessage NVARCHAR(4000) NULL,
	ErrorSeverity INT NULL,
	ErrorState INT NULL,
	ErrorLine INT NULL,
	ErrorProcedure NVARCHAR(256) NULL,
	CreatedLocalDate DATETIME2 NULL DEFAULT GETDATE(),
	CreatedUtcDate DATETIME2 NULL DEFAULT GETUTCDATE()
);


CREATE TABLE [dbo].[tbl_users](
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserName] [varchar](100) NOT NULL UNIQUE,
	[FullName] [varchar](200) NULL,
	[Email] [varchar](200) NULL,
	[EmailConfirmed] [bit] NULL,
	[CountryCallingCode] [varchar](10) NULL,
	[MobileNumber] [varchar](30) NULL,
	[MobileConfirmed] [bit] NULL,
	[Gender] [varchar](20) NULL,
	[Address] [varchar](500),
	[Department] [varchar](150) NULL,
	[DateOfBirth] [datetime2](7) NULL,
	[DateOfJoining] [datetime2](7) NULL,
	[PasswordHash] [nvarchar](512) NULL,
	[PasswordSalt] [nvarchar](MAX) NULL,	
	[AccessCodeHash] [nvarchar](512) NULL,
	[AccessCodeSalt] [nvarchar](MAX) NULL,
	[FailedLoginAttempt] [int] NULL,
	[TemporaryLockedTillUtcDate] [datetime2](7) NULL,	
	[ProfileImageUrlPath] [varchar](512) NULL,
	[LastIpAddress] [varchar](100) NULL,
	[DeviceId] [nvarchar](MAX) NULL,
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[IsBlocked] [bit] NULL,
	[LastLoginDateUtc] [datetime2](7) NULL,
	[LastActivityDateUtc] [datetime2](7) NULL,
	[CreatedBy] [varchar](100) NULL,	
	[CreatedLocalDate] [datetime2](7) NULL,
	[CreatedUtcDate] [datetime2](7) NULL,
	[CreatedNepaliDate] [varchar](20) NULL,
	[UpdatedBy] [varchar](100) NULL,
	[UpdatedLocalDate] [datetime2](7) NULL,
	[UpdatedUtcDate] [datetime2](7) NULL,
	[UpdatedNepaliDate] [varchar](20) NULL
)

	
create table tbl_roles
(
	Id int Identity(1,1) not null Primary key, 
	RoleName varchar(100) not null unique, 
	Description varchar(300),
	IsSystemRole bit,
	IsActive bit default(1),
	IsDeleted bit default(0),
	CreatedBy varchar(100),
	CreatedLocalDate datetime2(7),
	CreatedUtcDate datetime2(7),
	CreatedNepaliDate varchar(20),
	UpdatedBy varchar(100),
	UpdatedLocalDate datetime2(7),
	UpdatedUtcDate datetime2(7),
	UpdatedNepaliDate nvarchar(20)
)

	
create table tbl_user_roles
(
	UserId int FOREIGN KEY REFERENCES tbl_users(Id), 
	RoleId int FOREIGN KEY REFERENCES tbl_roles(Id)
)



create table tbl_document_type
(
	Id int Identity(1,1) Primary key,
	DocumentType varchar(100) not null unique,      --'Citizenship','Driving License','VoterId','Passport'
	DocumentTypeCode varchar(20) not null unique,	--'CTZNSHP','LICENSE','VOTERID','PASSPORT'
	IsExpirable bit,
	Remarks varchar(300),
	CreatedBy varchar(100),
	CreatedLocalDate datetime,
	CreatedUtcDate datetime,
	CreatedNepaliDate nvarchar(10),
	UpdatedBy varchar(100),
	UpdatedLocalDate datetime,
	UpdatedUtcDate datetime,
	UpdatedNepaliDate nvarchar(10)
)

CREATE TABLE [dbo].[tbl_remit_partners](
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[RemitPartnerCode] [varchar](20) NOT NULL,
	[UserName] [varchar](100) NOT NULL UNIQUE,
	[FullName] [varchar](200) NULL,
	[Email] [varchar](200) NULL,
	[EmailConfirmed] [bit] NULL,
	[CountryCallingCode] [varchar](10) NULL,
	[MobileNumber] [varchar](30) NULL,
	[MobileConfirmed] [bit] NULL,
	[Gender] [varchar](20) NULL,
	[Address] [varchar](500),
	--[Department] [varchar](150) NULL,
	[DateOfBirth] [datetime2](7) NULL,
	--[DateOfJoining] [datetime2](7) NULL,
	[PasswordHash] [nvarchar](512) NULL,
	[PasswordSalt] [nvarchar](MAX) NULL,	
	[AccessCodeHash] [nvarchar](512) NULL,
	[AccessCodeSalt] [nvarchar](MAX) NULL,
	[FailedLoginAttempt] [int] NULL,
	[TemporaryLockedTillUtcDate] [datetime2](7) NULL,	
	[ProfileImageUrlPath] [varchar](512) NULL,
	[NotificationBalance] [decimal](18,2) NULL,
	[ServiceChargeCategory] [varchar](50) NULL,
	[MarkupValue] [decimal](18,2) NULL,
	[OrganizationName] [varchar](256) NULL,
	[DirectorName] [varchar](200) NULL,
	[RegistrationNumber] [varchar](150) NULL,
	[OrganizationType] [varchar](50) NULL,
	[SourceCurrency] [varchar](3),
	[Website] [varchar](200) NULL,
	[IpAddress] [varchar](50) NULL,
	[CompanyLogoImgPath] [varchar](512) NULL,
	[LicenseDocumnetPathImgPath] [varchar](512) NULL,
	[DocumentTypeId] [int] foreign key references tbl_document_type(Id),
	[DocumentNumber] [varchar](150) NULL,
	[IdFrontImgPath] [varchar](512) NULL,
	[IdBackImgPath] [varchar](512) NULL,
	[ExpiryDate] [datetime2](7) NULL,
	[AddressProofTypeId] [int] NULL,
	[AddressProofImgPath] [varchar](512) NULL,
	[LastIpAddress] [varchar](100) NULL,
	[DeviceId] [nvarchar](MAX) NULL,
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[IsBlocked] [bit] NULL,
	[LastLoginDateUtc] [datetime2](7) NULL,
	[LastActivityDateUtc] [datetime2](7) NULL,
	[CreatedBy] [varchar](100) NULL,	
	[CreatedLocalDate] [datetime2](7) NULL,
	[CreatedUtcDate] [datetime2](7) NULL,
	[CreatedNepaliDate] [varchar](20) NULL,
	[UpdatedBy] [varchar](100) NULL,
	[UpdatedLocalDate] [datetime2](7) NULL,
	[UpdatedUtcDate] [datetime2](7) NULL,
	[UpdatedNepaliDate] [varchar](20) NULL
)


CREATE TABLE [dbo].[tbl_senders](
	[Id] [int] IDENTITY(1,1) NOT NULL primary key,
	[PartnerCode] [varchar](20) NOT NULL constraint FK_tbl_senders_remit_partner references tbl_remit_partners(PartnerCode),
	[MemberId] [varchar](20) NOT NULL unique,
	[FirstName] [nvarchar](100) NOT NULL,
	[SurName] [nvarchar](100) NULL,
	[IsSurNamePresent] [bit] NULL,
	[MobileNumber] [nvarchar](30) NULL,
	[Email] [nvarchar](200) NULL,
	[GenderId] [int] NULL,
	[DateOfBirth] [datetime] NULL,
	[ProfileImagePath] [nvarchar](500) NULL,
	[CountryCode] [varchar](10) NOT NULL constraint FK_tbl_senders_country references tbl_country(CountryCode),
	[Province] [nvarchar](150) NULL,
	[City] [nvarchar](150) NULL,
	[Zipcode] [nvarchar](50) NULL,
	[Address] [nvarchar](300) NULL,
	[OccupationId] [int] constraint FK_tbl_senders_occupation references tbl_occupation(Id),
	[DocumentTypeId] [int] NULL constraint FK_tbl_senders_document_type references tbl_document_type(Id),
	[DocumentNumber] [nvarchar](150) NULL,
	[IssuedDate] [datetime2](7) NULL,
	[ExpiryDate] [datetime2](7) NULL,
	[IdFrontImgPath] [nvarchar](512) NULL,
	[IdBackImgPath] [nvarchar](512) NULL,
	[BankName] [nvarchar](200) NULL,
	[BankCode] [nvarchar](50) NULL,
	[Branch] [nvarchar](200) NULL,
	[AccountHolderName] [nvarchar](200) NULL,
	[AccountNumber] [nvarchar](50) NULL,
	[IncomeSourceId] [int] constraint FK_tbl_senders_income_source references tbl_income_source(Id),
	[GMTTimeZone] [nvarchar](50) NULL,	
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[IsBlocked] [bit] NULL,	
	[KycStatusCode] [varchar](20) NULL,
	[Is2FAAuthenticated] [bit] NULL,
	[AccountSecretKey] [nvarchar](512) NULL,	
	[CreatedUserType] [varchar](50) NULL,
	[CreatedById] [int] NULL,
	[CreatedByName] [varchar](100) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[UpdatedUserType] [varchar](50) NULL,
	[UpdatedById] [int] NULL,
	[UpdatedByName] [varchar](100) NULL,
	[UpdatedDate] [datetime2](7) NULL
	)
GO

CREATE TABLE [dbo].[tbl_recipients](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SenderId] [int] constraint FK_tbl_recipients_senders references tbl_senders(Id),
	[FirstName] [nvarchar](100) NOT NULL,
	[SurName] [nvarchar](100) NULL,
	[IsSurNamePresent] [bit] NULL,
	[MobileNumber] [nvarchar](30) NULL,
	[Email] [nvarchar](200) NULL,
	[GenderId] [int] NULL,
	[DateOfBirth] [datetime] NULL,
	[CountryCode] [varchar](10) NOT NULL constraint FK_tbl_recipients_country references tbl_country(CountryCode),
	[ProvinceCode] [varchar](20) NULL,
	[DistrictCode] [varchar](20) NULL,
	[LocalBodyCode] [varchar](20) NULL,
	[City] [nvarchar](150) NULL,
	[Zipcode] [nvarchar](50) NULL,
	[Address] [nvarchar](300) NULL,
	[SourceCurrency] [varchar](3) NULL,
	[DestinationCurrency] [varchar](3) NULL,
	[RelationshipId] [int] constraint FK_tbl_recipients_relation references tbl_relation(Id),
	[PayoutTypeId] [int] constraint FK_tbl_recipients_payout references tbl_payment_type(Id),	
	[BankName] [nvarchar](200) NULL,
	[BankCode] [nvarchar](50) NULL,
	[Branch] [nvarchar](200) NULL,
	[AccountHolderName] [nvarchar](200) NULL,
	[AccountNumber] [nvarchar](50) NULL,
	[WalletName] [nvarchar](200) NULL,
	[WalletId] [nvarchar](50) NULL,
	[WalletRegisteredName] [nvarchar](150) NULL,	
	[GMTTimeZone] [nvarchar](50) NULL,	
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[IsBlocked] [bit] NULL,	
	[KycStatusCode] [varchar](20) NULL,	
	[CreatedUserType] [varchar](50) NULL,
	[CreatedById] [int] NULL,
	[CreatedByName] [varchar](100) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[UpdatedUserType] [varchar](50) NULL,
	[UpdatedById] [int] NULL,
	[UpdatedByName] [varchar](100) NULL,
	[UpdatedDate] [datetime2](7) NULL
	)
GO

CREATE TABLE [dbo].[tbl_remit_public_feedbacks](
	[FeedbackId] [int] IDENTITY(1001,1) PRIMARY KEY,
	[FullName] [nvarchar](128) NULL,
	[Email] [nvarchar](320) NULL,
	[ContactNo] [nvarchar](20) NULL,
	[Subject] [nvarchar](320) NULL,
	[Message] [nvarchar](2048) NULL,
	[IpAddress] [nvarchar](50) NULL,
	[IsReviewed] [bit] NULL DEFAULT 0,
	[ReviewedLocalDate] [datetime2](7) NULL,
	[UpdatedBy] [nvarchar](50) NULL,
	[CreatedLocalDate] [datetime2](7) NULL DEFAULT GETDATE(),
	[UpdatedLocalDate] [datetime2](7) NULL
)
GO